### ISSUE TITLE
Fallo al importar como PDF

### ISSUE THREAD

**Issue by FerminFB** [FerminFB/GestionVisualizacionDelProgramaEGC1718#1]
La funcionalidad de importar como PDF falla
![traza](https://user-images.githubusercontent.com/16592184/44222299-63fbc700-a184-11e8-8bda-ca07ea1c312a.png)

**Comment by enruiq** [comment]
A mi me funciona bien @FerminFB 
![2018-08-23_09h02_11](https://user-images.githubusercontent.com/23055516/44509889-5af28480-a6b3-11e8-925d-11a59d1f8604.png)

**Comment by FerminFB** [comment]
¿ Te funciona en local o heroku ?

**Comment by enruiq** [comment]
En Heroku. Pruébalo desde heroku para ver si te funciona a ti. Si no lo probaré por la tarde desde local. Aquí te dejo la url: https://programa-egc-septiembre.herokuapp.com/

**Comment by FerminFB** [comment]
Era un fallo en mi local. Cierro la issue
