### ISSUE TITLE
No se encuentra la funcionalidad de Google Calendar

### ISSUE THREAD

**Issue by enruiq** [FerminFB/GestionVisualizacionDelProgramaEGC1718#3]
En la descripción del proyecto, se destaca la funcionalidad de compartir y añadir el programa a Google Calendar, y esta funcionalidad no se ve reflejada en la aplicación. Esto habría que realizarlo desde 0.

**Comment by FerminFB** [comment]
La funcionalidad de Google Calendar no se ha podido implementar a tiempo para este Milestone
