### ISSUE TITLE
Servicio web

### ISSUE THREAD

**Issue by Juparor** [FerminFB/GestionVisualizacionDelProgramaEGC1718#4]
Se requiere la implementación de un servicio web que permita consumir el programa de las jornadas por parte de la aplicación Android atacando a la aplicación python.

**Comment by FerminFB** [comment]
Listo.
El servicio web se acaba de mergear a master
La URL seria https://programa-egc-septiembre.herokuapp.com/soap_service/?WSDL , en local seria 127.0.0.1:8000/soap_service/?WSDL

**Comment by Juparor** [comment]
Buenas tardes.

Sería necesario añadir un nuevo campo al contrato del servicio web en el cual se añada el código que enlaza las charlas con los eventos. Por ejemplo:
Monday 25 Sep 14:30 - 16:00 (M3.2) <-> (M3.2) Variability   Modeling with EASy-Producer Klaus Schmid and Holger Eichelberger

Un saludo!

**Comment by FerminFB** [comment]
Se ha añadido el campo a la respuesta del ws. La ultima entrada del array sería el campo que relaciona los dos objetos

**Comment by Juparor** [comment]
Se informa que se puede encontrar la parte implementada para relacionarse con el servicio web desde la aplicación android en el commit: https://github.com/Juparor/GestionVisualizacionDelProgramaEGC1718App/commit/1e64c565c4d6404164d7742cf8c7115f8106e82e
